# Generated by Django 4.2.1 on 2023-06-09 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('additional_information', '0002_rename_mail_questions_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
