# Generated by Django 4.2.1 on 2023-06-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_course', models.CharField(default='', max_length=20, verbose_name='Учебные курсы')),
            ],
        ),
        migrations.AddField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
