# Generated by Django 4.2.1 on 2023-06-02 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classroom', models.CharField(max_length=5, verbose_name='Номер аудитории')),
            ],
            options={
                'verbose_name': 'Номер учебной аудитории',
                'verbose_name_plural': 'Номера учебных аудиторий',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lesson', models.DateField(verbose_name='Дата урока')),
                ('number_of_slot', models.IntegerField(verbose_name='Порядковый номер учебного занятия')),
                ('info_for_lesson', models.TextField(blank=True, null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classroom', verbose_name='Учебная аудитория')),
                ('lesson_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lessonname', verbose_name='Предмет')),
                ('name_of_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studygroup', verbose_name='Учебная группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
