# Generated by Django 4.2.1 on 2023-06-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_headteacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headteacher',
            options={'verbose_name': 'Заведующий учебной частью', 'verbose_name_plural': 'Заведующие учебной частью'},
        ),
    ]
