# Generated by Django 4.2.1 on 2023-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_headteacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(related_name='Курсы', to='main.studygroup'),
        ),
    ]
