# Generated by Django 4.2.1 on 2023-06-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_course_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
    ]
