# Generated by Django 4.2.1 on 2023-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_teacher_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='headteacher',
            name='initials',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
