# Generated by Django 4.2.1 on 2023-06-07 12:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_headteacher_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/main/img/avatar.png', null=True, upload_to='user_avatars', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Начни с +7', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
