# Generated by Django 4.2.1 on 2023-06-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_advuser_avatar_alter_advuser_patronymic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name_of_group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
