# Generated by Django 4.2.1 on 2023-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_lesson_classroom_remove_lesson_lesson_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/main/img/avatar.png', null=True, upload_to='get_timestamp_path', verbose_name='Аватар пользователя'),
        ),
    ]
