# Generated by Django 4.2.1 on 2023-06-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_advuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='get_timestamp_path', verbose_name='Аватар пользователя'),
        ),
    ]
