# Generated by Django 4.2.1 on 2023-06-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0016_remove_lesson_classroom_remove_lesson_lesson_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classroom', models.CharField(max_length=5, verbose_name='Номер аудитории')),
            ],
            options={
                'verbose_name': 'Номер учебной аудитории',
                'verbose_name_plural': 'Номера учебных аудиторий',
            },
        ),
        migrations.CreateModel(
            name='StudyGroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название курса')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lesson', models.DateField(verbose_name='Дата урока')),
                ('number_of_slot', models.IntegerField(verbose_name='Порядковый номер учебного занятия')),
                ('info_for_lesson', models.TextField(blank=True, null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.classroom', verbose_name='Учебная аудитория')),
                ('lesson_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lessonname', verbose_name='Предмет')),
                ('name_of_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studygroup', verbose_name='Учебная группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Расписание курса',
                'verbose_name_plural': 'Расписание курсов',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lessons.studygroupschedule',),
        ),
        migrations.CreateModel(
            name='DayStudyGroupSchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Расписание дня',
                'verbose_name_plural': 'Расписание учебных дней',
                'ordering': ('schedule_of_course__order', 'schedule_of_course__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lessons.studygroupschedule',),
        ),
        migrations.AddField(
            model_name='studygroupschedule',
            name='schedule_of_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.courseschedule', verbose_name='Расписание курса'),
        ),
    ]
