# Generated by Django 4.2.1 on 2023-06-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroupschedule',
            name='schedule_of_course',
        ),
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
        migrations.DeleteModel(
            name='DayStudyGroupSchedule',
        ),
        migrations.DeleteModel(
            name='StudyGroupSchedule',
        ),
    ]
